import requests
import json
import time

BASE_URL = "http://localhost:8000"
CHAT_ENDPOINT = f"{BASE_URL}/api/builder/chat"

# Color codes for pretty printing
GREEN = "\033[92m"
CYAN = "\033[96m"
YELLOW = "\033[93m"
RED = "\033[91m"
RESET = "\033[0m"

def simulate_session():
    print(f"{GREEN}=== Starting Builder Co-Pilot Simulation ==={RESET}\n")
    
    # mimicks the frontend state
    # List of {id, framework, agents: []}
    current_flow_state = []
    
    # user prompts to simulate a full session
    scenario = [
        "I need a flow to create an SEO site map for a company.",
        "Split it into keywords using a debate, then use a specialized crew to write blogs and landing pages.",
        "Add a final step to verify the URL slugs with a standalone specialist."
    ]
    
    step_id_counter = 1

    for turn_idx, user_msg in enumerate(scenario):
        print(f"{CYAN}User: {user_msg}{RESET}")
        
        payload = {
            "message": user_msg,
            "current_flow": current_flow_state
        }
        
        try:
            # 1. Call API
            start_t = time.time()
            resp = requests.post(CHAT_ENDPOINT, json=payload)
            resp.raise_for_status()
            data = resp.json()
            duration = time.time() - start_t
            
            # 2. Show Thought
            thought = data.get("thought", "No thought provided.")
            actions = data.get("actions", [])
            print(f"{YELLOW}Co-Pilot ({duration:.1f}s): {thought}{RESET}")
            
            # 3. Simulate Frontend Execution
            for action in actions:
                cmd = action.get("cmd")
                print(f"  [ACTION] {action}")
                
                if cmd == "add_step":
                    # Frontend creates a new step div
                    # We mock this state
                    step_id = action.get("id")
                    # If ID not provided or "step_N", generated by logic, but usually agent provides it
                    # In our simple mock, we trust the agent's ID or generate one
                     # Real frontend logic: const step = createStep(act.framework); step.dataset.stepId = act.id;
                    new_step = {
                        "id": step_id, 
                        "framework": action.get("framework"),
                        "agents": [],
                        "io": {} 
                    }
                    current_flow_state.append(new_step)
                    
                elif cmd == "add_agent":
                    # Find step and add agent
                    s_id = action.get("step_id")
                    a_id = action.get("agent_id")
                    target = next((x for x in current_flow_state if x["id"] == s_id), None)
                    if target:
                        target["agents"].append(a_id)
                    else:
                        print(f"{RED}  [ERROR] Target step {s_id} not found!{RESET}")

                elif cmd == "set_io":
                    s_id = action.get("step_id")
                    io_type = action.get("type") # in/out
                    block = action.get("block")
                    target = next((x for x in current_flow_state if x["id"] == s_id), None)
                    if target:
                        target["io"][io_type] = block
            
            print(f"  {GREEN}-> State Updated. Current Flow Steps: {len(current_flow_state)}{RESET}\n")
            
        except Exception as e:
            print(f"{RED}CRASH: {e}{RESET}")
            if 'resp' in locals():
                print(f"Response: {resp.text}")
            break

    print(f"\n{GREEN}=== Simulation Complete ==={RESET}")
    print("Final State:")
    print(json.dumps(current_flow_state, indent=2))

if __name__ == "__main__":
    simulate_session()
