import asyncio
import os
import sys

# Adjust path to find modules
sys.path.append(os.getcwd())

from engines.routing.provider_router import ProviderRouter

async def test_router():
    print("Testing ProviderRouter...")
    # Adjust path to point to northstar-agents relative to northstar-engines/engines/routing
    # based on where we run this script. 
    # If we run from /Users/jaynowman/dev/northstar-engines, agents is at ../northstar-agents
    
    # We will run this from /Users/jaynowman/dev/northstar-engines
    router = ProviderRouter(agents_path="../northstar-agents")
    
    try:
        # Test 1: Load the specific card we created
        print("Attempting to route with 'routing.dev_free_tier_hunter'...")
        result = await router.route_request("routing.dev_free_tier_hunter", "Hello World", "TestAgent")
        print(f"Result: {result}")
        
        if "Generated by" in result:
            print("SUCCESS: Routing executed successfully.")
        else:
            print("FAILURE: Unexpected result format.")
            
    except Exception as e:
        print(f"FAILURE: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    asyncio.run(test_router())
