from unittest.mock import MagicMock, patch
from northstar.engines_boundary.client import EnginesBoundaryClient
from northstar.runtime.context import AgentsRequestContext, ContextMode


def test_get_canvas_snapshot():
    client = EnginesBoundaryClient("http://test.url")
    ctx = AgentsRequestContext(
        tenant_id="t1",
        mode=ContextMode.LAB,
        project_id="p1",
        request_id="r1",
        user_id="user",
    )

    with patch("httpx.request") as mock_req:
        mock_resp = MagicMock()
        mock_resp.is_error = False
        mock_resp.json.return_value = {"id": "foo", "nodes": []}
        mock_resp.content = b'{"id": "foo", "nodes": []}'
        mock_req.return_value = mock_resp

        result = client.get_canvas_snapshot("foo", ctx)

        assert result == {"id": "foo", "nodes": []}
        # Verify headers generated by to_headers + client defaults
        expected_headers = {
            "X-Tenant-Id": "t1",
            "X-Mode": "lab",
            "X-Project-Id": "p1",
            "X-Request-Id": "r1",
            "X-User-Id": "user",
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        mock_req.assert_called_with(
            "GET", "http://test.url/canvas/foo", headers=expected_headers, json=None
        )


def test_get_canvas_replay():
    client = EnginesBoundaryClient("http://test.url")
    ctx = AgentsRequestContext(
        tenant_id="t1",
        mode=ContextMode.LAB,
        project_id="p1",
        request_id="r1",
        user_id="user",
    )

    with patch("httpx.request") as mock_req:
        mock_resp = MagicMock()
        mock_resp.is_error = False
        mock_resp.json.return_value = [{"event": "e1"}]
        mock_resp.content = b'[{"event": "e1"}]'
        mock_req.return_value = mock_resp

        result = client.get_canvas_replay("foo", ctx)

        assert result == [{"event": "e1"}]
        # Same headers check
        expected_headers = {
            "X-Tenant-Id": "t1",
            "X-Mode": "lab",
            "X-Project-Id": "p1",
            "X-Request-Id": "r1",
            "X-User-Id": "user",
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        mock_req.assert_called_with(
            "GET",
            "http://test.url/canvas/foo/replay",
            headers=expected_headers,
            json=None,
        )
