"use client";

import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase';

// THE USER'S EXACT PROMPT
const MUSCLE_PROMPT = `You work ONLY inside /Users/jaynowman/dev/atoms-muscle.
Your job is to continuously build new “Muscles” (GPU/FFmpeg/Torch/etc tools) without interfering with any other repo work.
The automation pipeline must stay intact: service.py → sentinel → factory wrapper → registry sync.
Read first (do not start coding before reading)

Contract: AGENTS.md
Skill: SKILL.md
Sentinel: sentinel.py
Factory: factory.py
Registry sync (Supabase): sync_muscles.py
Hard guardrails (non‑negotiable)

NO .env / .env.* files anywhere.
Do not touch other repos (especially /Users/jaynowman/dev/atoms-core, /Users/jaynowman/dev/atoms-app, /Users/jaynowman/dev/northstar-*) unless explicitly instructed. Your scope is atoms-muscle only.
Do not invent new folder conventions. Follow the exact structure below.
Each new muscle must be atomic and self-contained (no cross-muscle hidden dependencies).
Where you must build muscles

All muscles live under: /Users/jaynowman/dev/atoms-muscle/src/{category}/{name}/
Each muscle directory must end up containing:
service.py (core implementation)
mcp.py (FastMCP wrapper; generated by factory if missing)
SKILL.md (skill packaging; generated by factory if missing, but you must ensure it’s accurate)
How to run the automation (mandatory)

Start the sentinel in one terminal:
sentinel.py
Create or edit your muscle implementation:
service.py
Confirm sentinel triggered:
It should create/confirm mcp.py + SKILL.md via factory.py
It should then run registry sync via sync_muscles.py
If vault keys aren’t available in your environment, validate scan logic with dry run:
sync_muscles.py
Definition of Done per muscle

service.py exists and has a clean, callable entry (e.g. class with run(...) -> dict or whatever the local pattern requires).
Sentinel generates (or you ensure) mcp.py and SKILL.md in the same folder.
Registry sync sees the muscle key and would upsert it (dry-run acceptable if keys missing).
No changes outside /Users/jaynowman/dev/atoms-muscle.
MUSCLE BRIEF (fill this in before you start)

Category (video/audio/image/cad/timeline/etc):
Muscle name (folder name):
What it does (1 paragraph):
Inputs (file types, params):
Outputs (artifacts + metadata):
Performance constraints (GPU? latency? batch?):
Any dependencies allowed (ffmpeg/torch/etc):
Example usage (one minimal example):`;

export default function MusclesConfigPage() {
    const router = useRouter();
    const supabase = createClient();
    const [muscles, setMuscles] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [showPrompt, setShowPrompt] = useState(false);

    useEffect(() => {
        supabase.auth.getUser().then(({ data: { user } }) => {
            if (!user) router.push('/login');
            else fetchMuscles();
        });
    }, []);

    const fetchMuscles = async () => {
        setLoading(true);
        const { data, error } = await supabase
            .from('muscles')
            .select('*')
            .order('key', { ascending: true });

        if (data) setMuscles(data);
        setLoading(false);
    };

    const copyPrompt = () => {
        navigator.clipboard.writeText(MUSCLE_PROMPT);
        alert("PROMPT COPIED TO CLIPBOARD");
    };

    // Group by Category
    const grouped = muscles.reduce((acc: any, m: any) => {
        const cat = (m.spec?.category || m.category || 'Uncategorized').toUpperCase();
        if (!acc[cat]) acc[cat] = [];
        acc[cat].push(m);
        return acc;
    }, {});

    const categories = Object.keys(grouped).sort();

    // Toggle State
    const [openCategories, setOpenCategories] = useState<Record<string, boolean>>({});

    const toggle = (cat: string) => {
        setOpenCategories(prev => ({ ...prev, [cat]: !prev[cat] }));
    };

    // Initialize all open on load
    useEffect(() => {
        if (categories.length > 0 && Object.keys(openCategories).length === 0) {
            const initial: Record<string, boolean> = {};
            categories.forEach(c => initial[c] = true);
            setOpenCategories(initial);
        }
    }, [muscles]);

    return (
        <div className="min-h-screen bg-graph-paper p-12 font-sans">
            <div className="max-w-6xl mx-auto bg-white border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] p-8">

                {/* HEADER */}
                <div className="flex justify-between items-start mb-8">
                    <div>
                        <h1 className="text-4xl font-black uppercase tracking-tighter leading-none mb-1">MUSCLE REGISTRY</h1>
                        <p className="font-bold text-xs tracking-widest uppercase text-neutral-500">HEAVY COMPUTE & MCP TOOLS</p>
                    </div>
                    <button
                        onClick={() => router.push('/god/config')}
                        className="px-6 py-2 border-2 border-black font-bold uppercase hover:bg-black hover:text-white transition-colors"
                    >
                        ← Back
                    </button>
                </div>

                {/* AUTOMATION STATUS CARD */}
                <div className="mb-4 bg-black text-green-400 font-mono p-4 border border-green-600 shadow-[0_0_15px_rgba(74,222,128,0.2)]">
                    <div className="flex justify-between items-center mb-2">
                        <span className="font-bold uppercase">● SENTINEL SYSTEM</span>
                        <span className="text-xs border border-green-600 px-2 py-0.5 rounded">ACTIVE</span>
                    </div>
                    <p className="text-xs opacity-80 mb-4">
                        The Sentinel watches <code>atoms-muscle</code> for new <code>service.py</code> files.
                        It automatically wraps them as MCP servers and registers them here.
                    </p>
                    <div className="bg-green-900/20 p-2 rounded text-xs select-all cursor-text">
                        $ python3 atoms-muscle/scripts/sentinel.py
                    </div>
                </div>

                {/* MUSCLE PROMPT LINK */}
                <div className="mb-8">
                    <button
                        onClick={() => setShowPrompt(!showPrompt)}
                        className="text-xs font-bold uppercase underline hover:text-blue-600 mb-2 block"
                    >
                        {showPrompt ? '- Hide Muscle Prompt' : '+ Muscle Prompt'}
                    </button>

                    {showPrompt && (
                        <div className="bg-neutral-100 border-2 border-black p-4 animate-in fade-in slide-in-from-top-2">
                            <div className="flex justify-between items-center mb-2">
                                <h4 className="font-bold text-sm uppercase">Agent Instructions</h4>
                                <button
                                    onClick={copyPrompt}
                                    className="bg-black text-white px-3 py-1 text-xs font-bold uppercase hover:opacity-80 disabled:opacity-50"
                                >
                                    Copy Text
                                </button>
                            </div>
                            <pre className="text-[10px] font-mono whitespace-pre-wrap h-48 overflow-y-auto bg-white border border-neutral-300 p-2 select-all">
                                {MUSCLE_PROMPT}
                            </pre>
                        </div>
                    )}
                </div>

                {/* CATEGORY DROP-DOWNS */}
                {loading ? (
                    <div className="font-mono animate-pulse">LOADING MUSCLES...</div>
                ) : (
                    <div className="space-y-4">
                        {categories.map(cat => (
                            <div key={cat} className="border-4 border-black">
                                <button
                                    onClick={() => toggle(cat)}
                                    className="w-full flex justify-between items-center p-6 bg-black text-white hover:bg-neutral-900 transition-colors uppercase font-black tracking-tighter text-xl"
                                >
                                    <span>{cat}_CORE // {grouped[cat].length} UNITS</span>
                                    <span>{openCategories[cat] ? '[-]' : '[+]'}</span>
                                </button>

                                {openCategories[cat] && (
                                    <div className="bg-neutral-100 p-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                                        {grouped[cat].map((m: any) => (
                                            <div key={m.id} className="bg-white border-2 border-black p-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all flex flex-col justify-between h-full">
                                                <div>
                                                    <div className="flex justify-between items-start mb-4">
                                                        <h3 className="font-black text-lg uppercase leading-tight">{m.name}</h3>
                                                        {m.spec?.mcp_endpoint ? (
                                                            <div className="w-3 h-3 bg-green-500 rounded-full border border-black animate-pulse" title="Online" />
                                                        ) : (
                                                            <div className="w-3 h-3 bg-neutral-300 rounded-full border border-black" title="Offline" />
                                                        )}
                                                    </div>

                                                    <p className="font-mono text-xs leading-relaxed text-neutral-600 mb-6 border-l-2 border-neutral-300 pl-3">
                                                        {m.spec?.description || 'Awaiting description override.'}
                                                    </p>
                                                </div>

                                                <div className="mt-auto pt-4 border-t-2 border-dashed border-neutral-200">
                                                    <div className="font-mono text-[10px] text-neutral-400 uppercase mb-1">MCP ENDPOINT</div>
                                                    <code className="block bg-neutral-100 p-1 text-[10px] truncate select-all border border-neutral-200">
                                                        {m.spec?.mcp_endpoint || 'N/A'}
                                                    </code>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
}
