"use client";

import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase';

// THE USER'S EXACT PROMPT
const MUSCLE_PROMPT = `You work ONLY inside /Users/jaynowman/dev/atoms-muscle.
Your job is to continuously build new “Muscles” (GPU/FFmpeg/Torch/etc tools) without interfering with any other repo work.
The automation pipeline must stay intact: service.py → sentinel → factory wrapper → registry sync.
Read first (do not start coding before reading)

Contract: AGENTS.md
Skill: SKILL.md
Sentinel: sentinel.py
Factory: factory.py
Registry sync (Supabase): sync_muscles.py
Hard guardrails (non‑negotiable)

NO .env / .env.* files anywhere.
Do not touch other repos (especially /Users/jaynowman/dev/atoms-core, /Users/jaynowman/dev/atoms-app, /Users/jaynowman/dev/northstar-*) unless explicitly instructed. Your scope is atoms-muscle only.
Do not invent new folder conventions. Follow the exact structure below.
Each new muscle must be atomic and self-contained (no cross-muscle hidden dependencies).
Where you must build muscles

All muscles live under: /Users/jaynowman/dev/atoms-muscle/src/muscle/{category}/{name}/
Each muscle directory must end up containing:
service.py (core implementation)
mcp.py (FastMCP wrapper; generated by factory if missing)
SKILL.md (skill packaging; generated by factory if missing, but you must ensure it’s accurate)
How to run the automation (mandatory)

Start the sentinel in one terminal:
sentinel.py
Create or edit your muscle implementation:
service.py
Confirm sentinel triggered:
It should create/confirm mcp.py + SKILL.md via factory.py
It should then run registry sync via sync_muscles.py
If vault keys aren’t available in your environment, validate scan logic with dry run:
sync_muscles.py
Definition of Done per muscle

service.py exists and has a clean, callable entry (e.g. class with run(...) -> dict or whatever the local pattern requires).
Sentinel generates (or you ensure) mcp.py and SKILL.md in the same folder.
Registry sync sees the muscle key and would upsert it (dry-run acceptable if keys missing).
No changes outside /Users/jaynowman/dev/atoms-muscle.
MUSCLE BRIEF (fill this in before you start)

Category (video/audio/image/cad/timeline/etc):
Muscle name (folder name):
What it does (1 paragraph):
Inputs (file types, params):
Outputs (artifacts + metadata):
Performance constraints (GPU? latency? batch?):
Any dependencies allowed (ffmpeg/torch/etc):
Example usage (one minimal example):`;

export default function MusclesConfigPage() {
    const router = useRouter();
    const supabase = createClient();
    const [muscles, setMuscles] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [showPrompt, setShowPrompt] = useState(false);

    useEffect(() => {
        supabase.auth.getUser().then(({ data: { user } }) => {
            if (!user) router.push('/login');
            else fetchMuscles();
        });
    }, []);

    const fetchMuscles = async () => {
        setLoading(true);
        const { data, error } = await supabase
            .from('muscles')
            .select('*')
            .order('key', { ascending: true });

        if (data) setMuscles(data);
        setLoading(false);
    };

    const copyPrompt = () => {
        navigator.clipboard.writeText(MUSCLE_PROMPT);
        alert("PROMPT COPIED TO CLIPBOARD");
    };

    return (
        <div className="min-h-screen bg-graph-paper p-12 font-sans">
            <div className="max-w-6xl mx-auto bg-white border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] p-8">

                {/* HEADER */}
                <div className="flex justify-between items-start mb-8">
                    <div>
                        <h1 className="text-4xl font-black uppercase tracking-tighter leading-none mb-1">MUSCLE REGISTRY</h1>
                        <p className="font-bold text-xs tracking-widest uppercase text-neutral-500">HEAVY COMPUTE & MCP TOOLS</p>
                    </div>
                    <button
                        onClick={() => router.push('/god/config')}
                        className="px-6 py-2 border-2 border-black font-bold uppercase hover:bg-black hover:text-white transition-colors"
                    >
                        ← Back
                    </button>
                </div>

                {/* AUTOMATION STATUS CARD */}
                <div className="mb-4 bg-black text-green-400 font-mono p-4 border border-green-600 shadow-[0_0_15px_rgba(74,222,128,0.2)]">
                    <div className="flex justify-between items-center mb-2">
                        <span className="font-bold uppercase">● SENTINEL SYSTEM</span>
                        <span className="text-xs border border-green-600 px-2 py-0.5 rounded">ACTIVE</span>
                    </div>
                    <p className="text-xs opacity-80 mb-4">
                        The Sentinel watches <code>atoms-muscle</code> for new <code>service.py</code> files.
                        It automatically wraps them as MCP servers and registers them here.
                    </p>
                    <div className="bg-green-900/20 p-2 rounded text-xs select-all cursor-text">
                        $ python3 atoms-muscle/scripts/sentinel.py
                    </div>
                </div>

                {/* MUSCLE PROMPT LINK */}
                <div className="mb-8">
                    <button
                        onClick={() => setShowPrompt(!showPrompt)}
                        className="text-xs font-bold uppercase underline hover:text-blue-600 mb-2 block"
                    >
                        {showPrompt ? '- Hide Muscle Prompt' : '+ Muscle Prompt'}
                    </button>

                    {showPrompt && (
                        <div className="bg-neutral-100 border-2 border-black p-4 animate-in fade-in slide-in-from-top-2">
                            <div className="flex justify-between items-center mb-2">
                                <h4 className="font-bold text-sm uppercase">Agent Instructions</h4>
                                <button
                                    onClick={copyPrompt}
                                    className="bg-black text-white px-3 py-1 text-xs font-bold uppercase hover:opacity-80 disabled:opacity-50"
                                >
                                    Copy Text
                                </button>
                            </div>
                            <pre className="text-[10px] font-mono whitespace-pre-wrap h-48 overflow-y-auto bg-white border border-neutral-300 p-2 select-all">
                                {MUSCLE_PROMPT}
                            </pre>
                        </div>
                    )}
                </div>

                {/* TABLE */}
                {loading ? (
                    <div className="font-mono animate-pulse">LOADING MUSCLES...</div>
                ) : (
                    <div className="overflow-x-auto">
                        <table className="w-full border-collapse text-left font-mono text-xs">
                            <thead>
                                <tr className="border-b-2 border-black bg-neutral-50">
                                    <th className="p-3 uppercase">KEY</th>
                                    <th className="p-3 uppercase">NAME</th>
                                    <th className="p-3 uppercase">MCP STATUS</th>
                                    <th className="p-3 uppercase">PRICING</th>
                                </tr>
                            </thead>
                            <tbody>
                                {muscles.map((m) => (
                                    <tr key={m.id} className="border-b border-black/10 hover:bg-yellow-50 transition-colors">
                                        <td className="p-3 font-bold">{m.key}</td>
                                        <td className="p-3">{m.name}</td>
                                        <td className="p-3">
                                            {m.spec?.mcp_endpoint ? (
                                                <span className="text-green-600 font-bold">● ONLINE</span>
                                            ) : (
                                                <span className="text-neutral-400">○ RAW</span>
                                            )}
                                        </td>
                                        <td className="p-3 opacity-60">
                                            {m.spec?.pricing || 'FREE'}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>
        </div>
    );
}
