from typing import Dict, Any
import time

class StubAgentRunner:
    """
    Simulates agent execution without calling LLMs.
    Verifies that required inputs are present and generates placeholder artifacts.
    """

    def run_agent_node(self, node: Any, inputs: Dict[str, Any], context: Any) -> Dict[str, Any]:
        print(f"[StubAgentRunner] Executing Agent Node: {node.node_id}")
        print(f"  - Persona: {node.persona_ref}")
        print(f"  - Task: {node.task_ref}")

        # Simulate processing time
        time.sleep(0.5)

        # Generate stub artifacts
        outputs = {}
        for artifact_def in node.artifact_outputs:
            stub_content = f"--- SIMULATED CONTENT FOR {artifact_def} ---\nGenerated by StubAgentRunner"
            outputs[artifact_def] = stub_content
            print(f"  - Generated artifact: {artifact_def}")

        print(f"[StubAgentRunner] Completed Node: {node.node_id}")
        return {
            "status": "success",
            "artifacts": outputs,
            "simulated": True
        }
