export type ToolKind = 'slider' | 'toggle' | 'enum' | 'action' | 'text';
export type ValueType = 'int' | 'float' | 'boolean' | 'string' | 'void';

export interface ToolDefinition {
    toolId: string;
    label: string;
    surfaceId: string;
    kind: ToolKind;
    valueType: ValueType;
    allowedOps: string[];
    options?: string[];
}

export const TOOL_REGISTRY: Record<string, ToolDefinition> = {
    'grid.cols_desktop': {
        toolId: 'grid.cols_desktop',
        label: 'Desktop Columns',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'grid.cols_mobile': {
        toolId: 'grid.cols_mobile',
        label: 'Mobile Columns',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'grid.gap_x_desktop': {
        toolId: 'grid.gap_x_desktop',
        label: 'Desktop Gap',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'grid.gap_x_mobile': {
        toolId: 'grid.gap_x_mobile',
        label: 'Mobile Gap',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'grid.gap_y_desktop': {
        toolId: 'grid.gap_y_desktop',
        label: 'Desktop Gap Y',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'grid.gap_y_mobile': {
        toolId: 'grid.gap_y_mobile',
        label: 'Mobile Gap Y',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'grid.tile_radius_desktop': {
        toolId: 'grid.tile_radius_desktop',
        label: 'Desktop Radius',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'grid.tile_radius_mobile': {
        toolId: 'grid.tile_radius_mobile',
        label: 'Mobile Radius',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'grid.aspect_ratio': {
        toolId: 'grid.aspect_ratio',
        label: 'Aspect Ratio',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['16:9', '4:3', '1:1', '9:16'],
    },
    'feed.query.limit_desktop': {
        toolId: 'feed.query.limit_desktop',
        label: 'Desktop Items',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'feed.query.limit_mobile': {
        toolId: 'feed.query.limit_mobile',
        label: 'Mobile Items',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    previewMode: {
        toolId: 'previewMode',
        label: 'Preview Mode',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['desktop', 'mobile'],
    },
    align: {
        toolId: 'align',
        label: 'Align',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['left', 'center', 'right'],
    },
    aspectRatio: {
        toolId: 'aspectRatio',
        label: 'Aspect Ratio',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['square', 'portrait', 'landscape'],
    },
    tileVariant: {
        toolId: 'tileVariant',
        label: 'Tile Variant',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['generic', 'product', 'kpi', 'text'],
    },
    showTitle: {
        toolId: 'showTitle',
        label: 'Show Title',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    'show_registry': {
        toolId: 'show_registry',
        label: 'Show Registry',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    showMeta: {
        toolId: 'showMeta',
        label: 'Show Meta',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    showBadge: {
        toolId: 'showBadge',
        label: 'Show Badge',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    showCtaLabel: {
        toolId: 'showCtaLabel',
        label: 'Show CTA Label',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    showCtaArrow: {
        toolId: 'showCtaArrow',
        label: 'Show CTA Arrow',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    'tile.toggleLock': {
        toolId: 'tile.toggleLock',
        label: 'Tile Lock',
        surfaceId: 'multi21.tile',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    'block.setSpanDesktop': {
        toolId: 'block.setSpanDesktop',
        label: 'Block Span Desktop',
        surfaceId: 'multi21.block',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'block.setSpanMobile': {
        toolId: 'block.setSpanMobile',
        label: 'Block Span Mobile',
        surfaceId: 'multi21.block',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'block.setTileVariant': {
        toolId: 'block.setTileVariant',
        label: 'Block Tile Variant',
        surfaceId: 'multi21.block',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['generic', 'product', 'kpi', 'text'],
    },
    'cta.width': {
        toolId: 'cta.width',
        label: 'CTA Width',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'cta.height': {
        toolId: 'cta.height',
        label: 'CTA Height',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'cta.scale': {
        toolId: 'cta.scale',
        label: 'CTA Scale',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'float',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'cta.variant': {
        toolId: 'cta.variant',
        label: 'CTA Variant',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['solid', 'outline', 'ghost', 'atomic'],
    },
    'cta.size': {
        toolId: 'cta.size',
        label: 'CTA Size',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['small', 'medium', 'large'],
    },
    'cta.fullWidth': {
        toolId: 'cta.fullWidth',
        label: 'CTA Full Width',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    'cta.align': {
        toolId: 'cta.align',
        label: 'CTA Align',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['left', 'center', 'right'],
    },
    'cta.content.label': {
        toolId: 'cta.content.label',
        label: 'CTA Label',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    // Phase 8: Style Tools (Chameleon Engine)
    'style.bg': {
        toolId: 'style.bg',
        label: 'Background Color',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    'style.block_bg': {
        toolId: 'style.block_bg',
        label: 'Block Background Color',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    'style.text': {
        toolId: 'style.text',
        label: 'Text Color',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    'style.text_stroke_color': {
        toolId: 'style.text_stroke_color',
        label: 'Text Stroke Color',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    'style.text_stroke_width': {
        toolId: 'style.text_stroke_width',
        label: 'Text Stroke Width',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'float',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    // Phase 10: Content & Feeds
    'content.feed_source_index': {
        toolId: 'content.feed_source_index',
        label: 'Feed Source',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'content.feed_limit': {
        toolId: 'content.feed_limit',
        label: 'Feed Limit',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'content.layout_mode': {
        toolId: 'content.layout_mode',
        label: 'Layout Mode',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'tile.variant': {
        toolId: 'tile.variant',
        label: 'Tile Variant',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['generic', 'product', 'kpi', 'text', 'video', 'youtube', 'events', 'blogs'],
    },
    'tile.show_title': {
        toolId: 'tile.show_title',
        label: 'Show Title',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    'tile.show_meta': {
        toolId: 'tile.show_meta',
        label: 'Show Meta',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    'tile.show_badge': {
        toolId: 'tile.show_badge',
        label: 'Show Badge',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    'tile.show_cta_label': {
        toolId: 'tile.show_cta_label',
        label: 'Show CTA Label',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    'tile.show_cta_arrow': {
        toolId: 'tile.show_cta_arrow',
        label: 'Show CTA Arrow',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    'style.accent': {
        toolId: 'style.accent',
        label: 'Funk Color',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    'style.border_color': {
        toolId: 'style.border_color',
        label: 'Border Color',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    'style.border_width': {
        toolId: 'style.border_width',
        label: 'Border Width',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'style.opacity': {
        toolId: 'style.opacity',
        label: 'Opacity',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'style.blur': {
        toolId: 'style.blur',
        label: 'Blur',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    // UI Global Tools
    'ui.show_tools': {
        toolId: 'ui.show_tools',
        label: 'Show Tools',
        surfaceId: 'multi21.shell',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    // Phase 12: Typography Tools (The Vario Engine)
    'typo.preset_index': {
        toolId: 'typo.preset_index',
        label: 'Font Preset',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'typo.size_desktop': {
        toolId: 'typo.size_desktop',
        label: 'Size Desktop',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'typo.size_mobile': {
        toolId: 'typo.size_mobile',
        label: 'Size Mobile',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'typo.line_height': {
        toolId: 'typo.line_height',
        label: 'Line Height',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'float',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'typo.tracking': {
        toolId: 'typo.tracking',
        label: 'Tracking',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'float',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'typo.word_spacing': {
        toolId: 'typo.word_spacing',
        label: 'Word Spacing',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'float',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'typo.stack_gap': {
        toolId: 'typo.stack_gap',
        label: 'Stack Gap',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },
    'typo.case': {
        toolId: 'typo.case',
        label: 'Text Case',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['none', 'uppercase', 'lowercase', 'capitalize'],
    },
    'typo.decoration': {
        toolId: 'typo.decoration',
        label: 'Text Decoration',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['none', 'underline', 'line-through'],
    },
    'typo.align': {
        toolId: 'typo.align',
        label: 'Text Align',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['left', 'center', 'right', 'justify'],
    },
    'typo.vert': {
        toolId: 'typo.vert',
        label: 'Vertical Align',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['top', 'center', 'bottom'],
    },
    'typo.family': {
        toolId: 'typo.family',
        label: 'Font Family',
        surfaceId: 'multi21.designer',
        kind: 'slider', // Index 0-3
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'typo.casual': {
        toolId: 'typo.casual',
        label: 'Casual Axis',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'float',
        allowedOps: ['setValue'],
    },
    'typo.slant': {
        toolId: 'typo.slant',
        label: 'Slant Axis',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'float',
        allowedOps: ['setValue'],
    },
    'typo.grade': {
        toolId: 'typo.grade',
        label: 'Grade Axis',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'float',
        allowedOps: ['setValue'],
    },
    'typo.weight': {
        toolId: 'typo.weight',
        label: 'Weight Axis',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'typo.width': {
        toolId: 'typo.width',
        label: 'Width Axis',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    // Phase 12: Text Content Tools
    'text.headline': {
        toolId: 'text.headline',
        label: 'Headline',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    'text.subhead': {
        toolId: 'text.subhead',
        label: 'Subhead',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    'text.body': {
        toolId: 'text.body',
        label: 'Body',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    // Copy Atom Tools
    'copy.text': {
        toolId: 'copy.text',
        label: 'Copy Text',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    'copy.level': {
        toolId: 'copy.level',
        label: 'Copy Level',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['h2', 'h3', 'h4', 'body'],
    },
    'copy.style': {
        toolId: 'copy.style',
        label: 'Copy Style',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['jumbo', 'headline', 'subtitle', 'tagline', 'quote', 'body', 'caption'],
    },
    'text.align': {
        toolId: 'text.align',
        label: 'Text Align',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['left', 'center', 'right', 'justify'],
    },
    'text.width': {
        toolId: 'text.width',
        label: 'Max Width',
        surfaceId: 'multi21.designer',
        kind: 'text', // Or slider
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    // Phase 13: Scoped Typography Tools (The Text Studio)
    'text.width_percent': {
        toolId: 'text.width_percent',
        label: 'Container Width',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue', 'increment', 'decrement'],
    },

    // --- Phase 14: CTA Tools ---
    'cta.variant': {
        toolId: 'cta.variant',
        label: 'Button Variant',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['solid', 'outline', 'ghost'],
    },
    'cta.size': {
        toolId: 'cta.size',
        label: 'Button Size',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['small', 'medium', 'large'],
    },
    'cta.fullWidth': {
        toolId: 'cta.fullWidth',
        label: 'Full Width',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    'cta.align': {
        toolId: 'cta.align',
        label: 'Button Alignment',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['left', 'center', 'right'],
    },
    // --- Headline ---
    'typo.headline.size_desktop': {
        toolId: 'typo.headline.size_desktop',
        label: 'Headline Size D',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'typo.headline.size_mobile': {
        toolId: 'typo.headline.size_mobile',
        label: 'Headline Size M',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'typo.headline.weight': {
        toolId: 'typo.headline.weight',
        label: 'Headline Weight',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    // --- Subhead ---
    'typo.subhead.size_desktop': {
        toolId: 'typo.subhead.size_desktop',
        label: 'Subhead Size D',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'typo.subhead.size_mobile': {
        toolId: 'typo.subhead.size_mobile',
        label: 'Subhead Size M',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'typo.subhead.weight': {
        toolId: 'typo.subhead.weight',
        label: 'Subhead Weight',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    // --- Body ---
    'typo.body.size_desktop': {
        toolId: 'typo.body.size_desktop',
        label: 'Body Size D',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'typo.body.size_mobile': {
        toolId: 'typo.body.size_mobile',
        label: 'Body Size M',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'typo.body.weight': {
        toolId: 'typo.body.weight',
        label: 'Body Weight',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    // --- Phase 18: Header & E-E-A-T Tools ---
    'header.layout': {
        toolId: 'header.layout',
        label: 'Header Layout',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['logo_left', 'logo_center', 'logo_split'],
    },
    'header.trust_signal': {
        toolId: 'header.trust_signal',
        label: 'Trust Signal',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['none', 'secure_icon', 'rating_star', 'verified_badge'],
    },
    'header.contact_priority': {
        toolId: 'header.contact_priority',
        label: 'Contact Priority',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['hidden', 'standard', 'highlight'],
    },
    'header.cta_mode': {
        toolId: 'header.cta_mode',
        label: 'CTA Mode',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['conversion', 'expertise'],
    },
    'nav.structure': {
        toolId: 'nav.structure',
        label: 'Nav Structure',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['flat', 'nested'],
    },
    'header.menu_source': {
        toolId: 'header.menu_source',
        label: 'Menu Source',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['main_site', 'landing_page', 'minimal'],
    },
    'header.sticky': {
        toolId: 'header.sticky',
        label: 'Sticky Header',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    // --- Phase 19: Popup & Data Tools ---
    'popup.trigger': {
        toolId: 'popup.trigger',
        label: 'Trigger',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['exit', 'timer', 'scroll', 'click', 'manual_teaser'],
    },
    'popup.delay': {
        toolId: 'popup.delay',
        label: 'Delay (Sec)',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'popup.frequency': {
        toolId: 'popup.frequency',
        label: 'Frequency',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['every_time', 'once_session', 'once_forever'],
    },
    'popup.position': {
        toolId: 'popup.position',
        label: 'Position',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['center', 'bottom_right', 'slide_in_left'],
    },
    'popup.teaser_text': {
        toolId: 'popup.teaser_text',
        label: 'Teaser Text',
        surfaceId: 'multi21.designer',
        kind: 'text',
        valueType: 'string',
        allowedOps: ['setValue'],
    },
    'popup.teaser_position': {
        toolId: 'popup.teaser_position',
        label: 'Teaser Position',
        surfaceId: 'multi21.designer',
        kind: 'enum',
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['bottom_left', 'bottom_right'],
    },
    'popup.overlay_opacity': {
        toolId: 'popup.overlay_opacity',
        label: 'Overlay Opacity',
        surfaceId: 'multi21.designer',
        kind: 'slider',
        valueType: 'int',
        allowedOps: ['setValue'],
    },
    'form.collect_utms': {
        toolId: 'form.collect_utms',
        label: 'Collect UTMs',
        surfaceId: 'multi21.designer',
        kind: 'toggle',
        valueType: 'boolean',
        allowedOps: ['setValue', 'toggle'],
    },
    'form.destination': {
        toolId: 'form.destination',
        label: 'Destination',
        surfaceId: 'multi21.designer',
        kind: 'enum', // Simplified as enum for now, or could be string input
        valueType: 'string',
        allowedOps: ['setValue', 'selectOption'],
        options: ['webhook', 'email', 'crm_id'],
    },
};

export function getToolDefinition(toolId: string): ToolDefinition | undefined {
    return TOOL_REGISTRY[toolId];
}
